use chrono::{DateTime, Utc};
use lasso::Spur;
use serde::{Deserialize, Serialize};
use timely::order::Product;
use uuid::Uuid;

/// Timestamp type used for differential-dataflow collections.
/// Combines a wall-clock time with a logical sequence number.
pub type DDTimestamp = Product<DateTime<Utc>, u64>;

/// Represents a single unprocessed log line.
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Hash)]
pub struct RawLog {
    pub content: String,
}

/// A tokenized log line with interned tokens.
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Hash)]
pub struct TokenizedLog {
    /// Unique identifier linking this tokenized log back to the source line.
    pub original_id: Uuid,
    /// Tokens produced from the log content using string interning.
    pub tokens: Vec<Spur>,
    /// Convenience field storing the number of tokens.
    pub token_count: usize,
}

/// Representation of a log template generated by clustering.
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Hash)]
pub struct LogTemplate {
    pub template_id: Uuid,
    /// Concrete and wildcard tokens forming the template.
    pub template_tokens: Vec<Spur>,
    pub token_count: usize,
}

/// Output structure connecting a template with aggregate statistics.
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Hash)]
pub struct LogCluster {
    pub template_id: Uuid,
    pub template_tokens: Vec<Spur>,
    /// Number of events that matched this template.
    pub event_count: u64,
    /// Sample raw log lines for reference.
    pub samples: Vec<String>,
}
